services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project-p3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password
      

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
